version: '3.9'
name: 'rinha-cleidiano'

services:
  api1: &api
    image: rinhabackend-2401:latest
    hostname: api1
    container_name: rinhaapi1
    environment:
      - DATASOURCE_DB_URL=jdbc:postgresql://postgres-db:5432/rinha
      - JAVA_OPTS=-javaagent:/opt/app/otel-javaagent.jar -Dio.ktor.development=false
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jaeger:4319
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8081:8080"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '145MB'
  api2:
    <<: *api
    hostname: api2
    container_name: rinhaapi2
    ports:
      - "8082:8080"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "10MB"

  postgres-db:
    image: postgres:latest
    container_name: rinhadb
    command: 'postgres -c max_connections=1000 -c shared_buffers=100MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./sql/ddl.sql:/docker-entrypoint-initdb.d/01-ddl.sql:ro
      - ./sql/criartransacao.sql:/docker-entrypoint-initdb.d/11-criartransacao.sql:ro
      - ./sql/resetdb.sql:/docker-entrypoint-initdb.d/21-resetdb.sql:ro
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '250MB'
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "rinha"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
networks:
  default:
    driver: bridge
    name: rinha-2024q1
