version: '3.9'
name: 'rinha-cleidiano'

services:
  api1: &api
    image: rinhabackend-2401:latest
    hostname: api1
    container_name: rinhaapi1
    environment:
      - DATASOURCE_DB_URL=jdbc:postgresql://postgres-db:5432/rinha
    depends_on:
      db:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '80MB'

  api2:
    <<: *api
    hostname: api2
    container_name: rinhaapi2

  postgres-db:
    image: postgres:latest
    container_name: rinhadb
    command: 'postgres -c max_connections=1000 -c shared_buffers=100MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./sql/ddl.sql:/docker-entrypoint-initdb.d/01-ddl.sql:ro
      - ./sql/criartransacao.sql:/docker-entrypoint-initdb.d/11-criartransacao.sql:ro
      - ./sql/resetdb.sql:/docker-entrypoint-initdb.d/21-resetdb.sql:ro
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256MB'
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "rinha"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
